export const options = [{
  title: 'Vanilla MuseNet',
  icon: { name: 'subject' },
  children: [{
      title: "Composer",
      interactive: true,
      stowed: true,
      toParam: "composer",
      inputType: "select",
      options: [
        'chopin',
        'mozart',
        'rachmaninoff',
        'country',
        'bach',
        'beethoven',
        'thebeatles',
        'franksinatra',
        'tchaikovsky'
      ],
      default: 'beethoven',
      info_title: "The style of music for MuseNet to select.",
      info_body: "",
    },
    {
      title: "Instruments",
      interactive: true,
      stowed: true,
      toParam: "instrumentation",
      inputType: "checkboxinput",
      options: [
        'piano',
        'strings',
        'winds',
        'drums',
        'harp',
        'guitar',
        'bass',
      ],
      default: ['piano', 'strings'],
      info_title: "MuseNet will attempt to generate a song with the checked instruments.",
      info_body: "",
    },
  ]
},
{
  title: "Shape & Form",
  icon: { name: "playlist_add" },
  children: [
    {
      title: "Temperature",
      interactive: true,
      stowed: true,
      toParam: "temp",
      inputType: "slider",
      min: .5,
      max: 1.5,
      default: .9,
      info_title: "Higher value = more randomness in generation",
      info_body: "A higher temperature will lead to more experimental outputs, while a smaller temperature might lead to overfitting.",

    },
    {
      title: "Tokens",
      interactive: true,
      stowed: true,
      toParam: "num_tokens",
      inputType: "slider",
      min: 5,
      max: 220,
      default: 215,
      info_title: "length of notes requested",
      info_body: "",
    },
  ]
},
]
